name: OCI Registry
description: Run a local OCI registry in docker
branding:
  icon: refresh-cw
  color: green
inputs:
  image:
    description: Registry image to run
    required: true
    type: string
    default: :2
  name:
    description: Container name, only needs to be defined when multiple registries are run
    required: true
    type: string
    default: default
  secure:
    description: When true, use https instead of http
    required: true
    type: bool
    default: true
  hostname:
    description: Hostname to map to the registry
    required: true
    type: string
    default: registry.local
  port:
    description: Port to listen on, defaults to 443 for secure and 80 for insecure
    required: true
    type: int
    default: 0
  tls-cert:
    description: Path to the PEM encoded, TSL certificate file. Must be set if tls-key is set
    type: string
  tls-key:
    description: Path to the PEM encoded, TSL key file. Must be set if tls-cert is set
    type: string
outputs:
  hostname:
    description: Registry hostname
    value: ${{ steps.run.outputs.hostname }}
  registry:
    description: Registry coordinates, including port if needed 
    value: ${{ steps.run.outputs.registry }}
  tls-ca:
    description: Path to certificate authority used by the registry
    value: ${{ steps.generate-certs.outputs.tls-ca }}
  tls-ca-raw:
    description: PEM encoded certificate authority used by the registry
    value: ${{ steps.generate-certs.outputs.tls-ca-raw }}
runs:
  using: "composite"
  steps:
    - name: Prep
      run: |
        set -o errexit
        set -o nounset
        set -o pipefail

        code=0

        if [[ "${{ inputs.secure }}" == "false" ]]; then
          if [[ "${{ inputs.tls-cert }}" != "" ]]; then
            echo "::warning title=tls-cert ignored::the tls-cert input is ignored for insecure registries"
          fi
          if [[ "${{ inputs.tls-key }}" != "" ]]; then
            echo "::warning title=tls-key ignored::the tls-key input is ignored for insecure registries"
          fi
        else
          if [[ "${{ inputs.tls-cert }}" == "" && "${{ inputs.tls-key }}" != "" ]]; then
            echo "::error title=tls-cert missing::the tls-cert input is required when the tls-key input is set"
            code=1
          elif [[ "${{ inputs.tls-cert }}" != "" && "${{ inputs.tls-key }}" == "" ]]; then
            echo "::error title=tls-key missing::the tls-key input is required when the tls-cert input is set"
            code=1
          fi
        fi

        if [[ "${{ inputs.port }}" -lt "0" || "${{ inputs.port }}" -gt "65535" ]]; then
          echo "::error title=invalid port::the port input must be between 0 and 65535"
          code=1
        fi

        exit ${code}
      shell: bash
    - name: Generate certs
      id: generate-certs
      if: inputs.secure && !inputs.tls-key
      uses: ./.github/actions/with-post-step
      with:
        main: ${{ github.action_path }}/scripts/generate-certs.sh "${{ inputs.name }}" "${{ inputs.hostname }}"
        post: ${{ github.action_path }}/scripts/cleanup-certs.sh "${{ inputs.name }}"
    - name: Run registry
      id: run
      uses: ./.github/actions/with-post-step
      with:
        main: ${{ github.action_path }}/scripts/start-registry.sh "${{ inputs.name }}" "${{ inputs.hostname }}" "${{ inputs.port }}" "${{ inputs.image }}" "${{ inputs.secure }}" "${{ inputs.tls-cert }}" "${{ inputs.tls-key }}"
        post: ${{ github.action_path }}/scripts/stop-registry.sh "${{ inputs.name }}" "${{ inputs.hostname }}"
