name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
    tags:
    # semver tags
    - 'v[0-9]+(\.[0-9]+\.[0-9]+-?**)?'
  pull_request: {}

jobs:
  test:
    name: Test registry action
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-24.04
        - ubuntu-22.04
        - ubuntu-24.04-arm
        - ubuntu-22.04-arm
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: OCI registry
      id: registry
      uses: ./
    - name: Install crane
      run: |
        set -o errexit
        set -o nounset
        set -o pipefail
        
        version=$(curl -s https://api.github.com/repos/google/go-containerregistry/releases/latest | jq -r .tag_name)
        os="$(uname)"
        arch="$(arch)"
        if [[ "${arch}" == "aarch64" ]]; then
            arch=arm64
        fi

        url="https://github.com/google/go-containerregistry/releases/download/${version}/go-containerregistry_${os}_${arch}.tar.gz"

        echo "Downloading ${url}"
        curl --fail -L "${url}" \
            | tar -xzf - crane
        mv crane /usr/local/bin
    - name: Use registry
      run: |
        set -o errexit
        set -o nounset
        set -o pipefail

        crane copy ubuntu ${{ steps.registry.outputs.registry }}/tests/ubuntu
        crane digest ${{ steps.registry.outputs.registry }}/tests/ubuntu
    - name: Show registry outputs
      run: |
        set -o errexit
        set -o nounset
        set -o pipefail

        echo "hostname: ${{ steps.registry.outputs.hostname }}"
        echo "registry: ${{ steps.registry.outputs.registry }}"
        echo "tls-ca: ${{ steps.registry.outputs.tls-ca }}"
        echo "tls-ca-raw: ${{ steps.registry.outputs.tls-ca-raw }}"
        echo ""
        echo "${{ toJSON(steps.registry.outputs) }}"
